### ISSUE TITLE
Issue in admin view of adding new post

### ISSUE THREAD

**Issue by poudelprakash** [kuyio/bloak#1]
![Screenshot 2023-05-25 at 7 47 23 PM](https://github.com/kuyio/bloak/assets/6129641/837f897f-4ad1-426b-a68b-cdb164b2c0c5)

Showing /Users/prakash/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/bloak-a4c1e81ffbbd/app/views/bloak/admin/posts/_form.html.erb where line #29 raised:

wrong number of arguments (given 1, expected 0)
Extracted source (around line #29):
      <div class="field mb-3">
        <%= form.label :published_at, class: 'form-label' %>
        <%= form.date_field(:published_at, class: 'form-control', value: (DateTime.now.to_s(:friendly_short) unless post.published_at.present?)) %>
      </div>
    </div>
  </div>

Tip: You may want to add gem 'error_highlight', '>= 0.4.0' into your Gemfile, which will display the fine-grained error location.

Trace of template inclusion: #<ActionView::Template /Users/prakash/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/bloak-a4c1e81ffbbd/app/views/bloak/admin/posts/new.html.erb locals=[]>

Rails.root: /Users/prakash/workspaces/2023/invoice-work/eboshi

Application Trace | Framework Trace | Full Trace
bloak (a4c1e81ffbbd) app/views/bloak/admin/posts/_form.html.erb:29:in `to_s'
bloak (a4c1e81ffbbd) app/views/bloak/admin/posts/_form.html.erb:29
rails (2dbc7dbac886) actionview/lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
rails (2dbc7dbac886) actionview/lib/action_view/buffers.rb:75:in `capture'
rails (2dbc7dbac886) actionview/lib/action_view/helpers/capture_helper.rb:50:in `capture'
rails (2dbc7dbac886) actionview/lib/action_view/helpers/form_helper.rb:773:in `form_with'
bloak (a4c1e81ffbbd) app/views/bloak/admin/posts/_form.html.erb:1
rails (2dbc7dbac886) actionview/lib/action_view/base.rb:264:in `public_send'
rails (2dbc7dbac886) actionview/lib/action_view/base.rb:264:in `_run'
rails (2dbc7dbac886) actionview/lib/action_view/template.rb:207:in `block in render'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:208:in `instrument'
rails (2dbc7dbac886) actionview/lib/action_view/template.rb:488:in `instrument_render_template'
rails (2dbc7dbac886) actionview/lib/action_view/template.rb:201:in `render'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/partial_renderer.rb:252:in `block in render_partial_template'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `instrument'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/partial_renderer.rb:237:in `render'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/renderer.rb:55:in `render_partial'
rails (2dbc7dbac886) actionview/lib/action_view/helpers/rendering_helper.rb:44:in `render'
bloak (a4c1e81ffbbd) app/views/bloak/admin/posts/new.html.erb:17
rails (2dbc7dbac886) actionview/lib/action_view/base.rb:264:in `public_send'
rails (2dbc7dbac886) actionview/lib/action_view/base.rb:264:in `_run'
rails (2dbc7dbac886) actionview/lib/action_view/template.rb:207:in `block in render'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:208:in `instrument'
rails (2dbc7dbac886) actionview/lib/action_view/template.rb:488:in `instrument_render_template'
rails (2dbc7dbac886) actionview/lib/action_view/template.rb:201:in `render'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `instrument'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `instrument'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/template_renderer.rb:11:in `render'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/renderer.rb:63:in `render_template_to_object'
rails (2dbc7dbac886) actionview/lib/action_view/renderer/renderer.rb:31:in `render_to_object'
rails (2dbc7dbac886) actionview/lib/action_view/rendering.rb:135:in `block in _render_template'
rails (2dbc7dbac886) actionview/lib/action_view/base.rb:291:in `in_rendering_context'
rails (2dbc7dbac886) actionview/lib/action_view/rendering.rb:134:in `_render_template'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/streaming.rb:231:in `_render_template'
rails (2dbc7dbac886) actionview/lib/action_view/rendering.rb:121:in `render_to_body'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/rendering.rb:158:in `render_to_body'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
rails (2dbc7dbac886) actionpack/lib/abstract_controller/rendering.rb:27:in `render'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/rendering.rb:139:in `render'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/instrumentation.rb:29:in `block (2 levels) in render'
/Users/prakash/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
rails (2dbc7dbac886) activesupport/lib/active_support/core_ext/benchmark.rb:14:in `ms'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/instrumentation.rb:29:in `block in render'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/instrumentation.rb:98:in `cleanup_view_runtime'
rails (2dbc7dbac886) activerecord/lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/instrumentation.rb:28:in `render'
meta-tags (2.18.0) lib/meta_tags/controller_helper.rb:22:in `render'
wicked_pdf (2.6.3) lib/wicked_pdf/pdf_helper.rb:18:in `render'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/implicit_render.rb:37:in `default_render'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/basic_implicit_render.rb:7:in `send_action'
rails (2dbc7dbac886) actionpack/lib/abstract_controller/base.rb:222:in `process_action'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/rendering.rb:165:in `process_action'
rails (2dbc7dbac886) actionpack/lib/abstract_controller/callbacks.rb:259:in `block in process_action'
rails (2dbc7dbac886) activesupport/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
rails (2dbc7dbac886) actiontext/lib/action_text/rendering.rb:23:in `with_renderer'
rails (2dbc7dbac886) actiontext/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
rails (2dbc7dbac886) activesupport/lib/active_support/callbacks.rb:130:in `instance_exec'
rails (2dbc7dbac886) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
rails (2dbc7dbac886) activesupport/lib/active_support/callbacks.rb:141:in `run_callbacks'
rails (2dbc7dbac886) actionpack/lib/abstract_controller/callbacks.rb:258:in `process_action'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/rescue.rb:25:in `process_action'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (2dbc7dbac886) activesupport/lib/active_support/notifications.rb:206:in `instrument'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/instrumentation.rb:73:in `process_action'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
rails (2dbc7dbac886) activerecord/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
rails (2dbc7dbac886) actionpack/lib/abstract_controller/base.rb:158:in `process'
rails (2dbc7dbac886) actionview/lib/action_view/rendering.rb:40:in `process'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal.rb:223:in `dispatch'
rails (2dbc7dbac886) actionpack/lib/action_controller/metal.rb:294:in `dispatch'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/routing/route_set.rb:32:in `serve'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/journey/router.rb:51:in `block in serve'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/journey/router.rb:32:in `each'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/journey/router.rb:32:in `serve'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/routing/route_set.rb:882:in `call'
rails (2dbc7dbac886) railties/lib/rails/engine.rb:529:in `call'
rails (2dbc7dbac886) railties/lib/rails/railtie.rb:226:in `public_send'
rails (2dbc7dbac886) railties/lib/rails/railtie.rb:226:in `method_missing'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/routing/mapper.rb:51:in `serve'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/journey/router.rb:51:in `block in serve'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/journey/router.rb:32:in `each'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/journey/router.rb:32:in `serve'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/routing/route_set.rb:882:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.0.7) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.0.7) lib/rack/etag.rb:29:in `call'
rack (3.0.7) lib/rack/conditional_get.rb:31:in `call'
rack (3.0.7) lib/rack/head.rb:15:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/http/permissions_policy.rb:39:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/http/content_security_policy.rb:37:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/cookies.rb:687:in `call'
rails (2dbc7dbac886) activerecord/lib/active_record/migration.rb:621:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
rails (2dbc7dbac886) activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
rails (2dbc7dbac886) railties/lib/rails/rack/logger.rb:37:in `call_app'
rails (2dbc7dbac886) railties/lib/rails/rack/logger.rb:24:in `block in call'
rails (2dbc7dbac886) activesupport/lib/active_support/tagged_logging.rb:135:in `block in tagged'
rails (2dbc7dbac886) activesupport/lib/active_support/tagged_logging.rb:39:in `tagged'
rails (2dbc7dbac886) activesupport/lib/active_support/tagged_logging.rb:135:in `tagged'
rails (2dbc7dbac886) railties/lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.0.7) lib/rack/method_override.rb:28:in `call'
rack (3.0.7) lib/rack/runtime.rb:24:in `call'
rails (2dbc7dbac886) activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.0.7) lib/rack/sendfile.rb:114:in `call'
rails (2dbc7dbac886) actionpack/lib/action_dispatch/middleware/host_authorization.rb:140:in `call'
rack-mini-profiler (3.1.0) lib/mini_profiler.rb:413:in `call'
rails (2dbc7dbac886) railties/lib/rails/engine.rb:529:in `call'
puma (6.2.2) lib/puma/configuration.rb:270:in `call'
puma (6.2.2) lib/puma/request.rb:98:in `block in handle_request'
puma (6.2.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (6.2.2) lib/puma/request.rb:97:in `handle_request'
puma (6.2.2) lib/puma/server.rb:431:in `process_client'
puma (6.2.2) lib/puma/server.rb:233:in `block in run'
puma (6.2.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Request
Parameters:

None
Toggle session dump
Toggle env dump
Response
Headers:

None

**Comment by poudelprakash** [comment]
`DateTime.now.to_s(:friendly_short)` is no more valid

ruby: 3.2.2
rails: 7.1.0 alpha

**Comment by nicbet** [comment]
Fixed in 2a1c7b8930c8b2a7667185e9b731184f15acd106
